# Autogenerated wrapper script for librttopo_jll for x86_64-w64-mingw32
export librttopo

using GEOS_jll
JLLWrappers.@generate_wrapper_header("librttopo")
JLLWrappers.@declare_library_product(librttopo, "librttopo-1.dll")
function __init__()
    JLLWrappers.@generate_init_header(GEOS_jll)
    JLLWrappers.@init_library_product(
        librttopo,
        "bin\\librttopo-1.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
