# Autogenerated wrapper script for librttopo_jll for x86_64-unknown-freebsd
export librttopo

using GEOS_jll
JLLWrappers.@generate_wrapper_header("librttopo")
JLLWrappers.@declare_library_product(librttopo, "librttopo.so.1")
function __init__()
    JLLWrappers.@generate_init_header(GEOS_jll)
    JLLWrappers.@init_library_product(
        librttopo,
        "lib/librttopo.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
